### PR TITLE
Remove dependency on SortedSet

### LINKED ISSUE #213: Consider dropping external deps: sorted_set and rbtree dependencies?
Would it be possible to drop `sorted_set` and `rbtree` dependencies for a couple reasons as `sorted_set` and `rbtree`? 

> It required RBTree to perform decently and the external dependency was not suitable for a standard library. The pure ruby fallback implementation was originally meant to be a demonstration of how to write a subclass of Set, and its poor performance was not suitable for use in production.

https://github.com/ruby/set/pull/2#issue-705226116

It also causes issue catastrophic segmentation fault https://github.com/knu/sorted_set/issues/13

### PR DESCRIPTION
**Pull request by rmm5t**
### 🚨 This is currently an experiment. 🚨

This is an experiment open for discussion and review. I'm not yet sure that this is the best approach, but the discussion in #213 got me thinking. Less external dependencies are usually better, and I'm not sure we were gaining a ton by using `SortedSet`. Now that `SortedSet` is no longer part of core ruby, these seems like a reasonable trade-off to eliminate its usage.

## What does it do?

- Removes external dependency on `SortedSet`

## What else do you need to know?

- `SortedSet` and is no longer part of core Ruby. 
- `SortedSet` relies on `RBTree` to perform
- I don't think we were gaining anything by using a `SortedSet` vs a regular `Set`

## Related Issues

- Fixes #213  (/cc @kimyu92)

### CODE REVIEW

File: lib/business_time/config.rb [hunk 1]
```diff
@@ -144,7 +144,7 @@ def weekdays
           wday_to_int(day_name)
         end.compact
 
-        self._weekdays = SortedSet.new(days)
+        self._weekdays = Set.new(days.sort)
```
Comment (kimyu-ng) [inline lib/business_time/config.rb]: Alternatively,

```suggestion
        self._weekdays = days.sort.to_set
```

**Review by kimyu-ng — APPROVED** [review]
Considering the benefits of dropping two non-core dependencies 🎉 . I agree we definitely want to call out in release note.

Since set is ordered in ruby, the interface is still mostly preserved. We also have specs coverage for these, I won't worry too much though 🙂 

LGTM  👍

**Comment by rmm5t** [comment]
@kimyu92 Could you please do me a favor, and test this branch on your project(s) that rely on business_time?

```ruby
gem "business_time", github: "bokmann/business_time", branch: "remove-sorted-set"
```

**Comment by kimyu-ng** [comment]
> Could you please do me a favor, and test this branch on your project(s) that rely on business_time?

That's exactly what I did last night against your branch. It works fine in my project 🙂

**Comment by kimyu-ng** [comment]
Update: Validated again. It's all ✅ on my end

**Comment by kimyu-ng** [comment]
What would be the timeline to get this in? 

It would be nice to get an official release 1.0.0 😂 instead of pointing to this branch for production grade project

**Comment by rmm5t** [comment]
@kimyu92 I'm planning on testing this with a couple of my own projects today. 

My original plans were going to make this a v1.0.0 release, but I've since changed my mind. I'm going to make this a v0.12.0 release and wait a few weeks or so to make sure that unsorted `holidays` doesn't break the internet. 😉

After that, I think a v1.0.0 release is warranted for this gem.

**Comment by fonji** [comment]
Hi! Any plan on merging this? :pray:

**Comment by rmm5t** [comment]
> Hi! Any plan on merging this? 🙏

I totally forgot about this. Thanks for the nudge.

**Comment by fonji** [comment]
Woah thank you!

**Comment by rmm5t** [comment]
v0.12.0 released. Please note the warnings in the [CHANGELOG](https://github.com/bokmann/business_time/blob/develop/CHANGELOG.md#0120---2022-06-07)
